---
label: Config
hide_body: true
fields:
- type: text
  name: label
  label: label
- type: boolean
  name: hide_body
  label: hide_body
- type: field_group_list
  name: fields
  label: fields
  fields:
  - type: text
    name: type
    label: type
  - type: text
    name: name
    label: name
  - type: text
    name: label
    label: label
- type: list
  name: pages
  label: pages
pages:
- data/test.md
